export const FETCH_OAUTH_TRIGGER = 'FETCH_OAUTH_TRIGGER';

export const FETCH_OAUTH_START = 'FETCH_OAUTH_START';

export const FETCH_OAUTH_SUCCESS = 'FETCH_OAUTH_SUCCESS';

export const FETCH_OAUTH_FAILURE = 'FETCH_OAUTH_FAILURE';

export const HANDLE_STRIPE_TOKEN = 'HANDLE_STRIPE_TOKEN';
