export const FETCH_SURVEYS_TRIGGER = 'FETCH_SURVEYS_TRIGGER';

export const FETCH_SURVEYS_START = 'FETCH_SURVEYS_START';

export const FETCH_SURVEYS_SUCCESS = 'FETCH_SURVEYS_SUCCESS';

export const FETCH_SURVEYS_FAILURE = 'FETCH_SURVEYS_FAILURE';
